name: Pineapple
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.7
  - pip
  - numpy
  - scipy
  - jpype1
  - numpy
  - geopandas
  - pandas
  - libpysal
  - matplotlib
  - openjdk=8
  - pip:
    - git+https://github.com/MagdyLab/Pyneapple.git@main
